/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author neexal
 */


import java.util.concurrent.ThreadLocalRandom;

public class GameWindow extends javax.swing.JFrame {

    /**
     * Creates new form GameWindow
     */
    String Comp;
    int chc ;
    public GameWindow() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(1000,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblPlayer = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblComputer = new javax.swing.JLabel();
        lblResult = new javax.swing.JPanel();
        lblRes = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnRock = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnPaper = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btnScissors = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rock Paper Scissors");

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Rock Paper Scissors");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(3, 3, 2, 2));

        jPanel3.setLayout(new java.awt.BorderLayout());

        lblPlayer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icons8_user_40px.png"))); // NOI18N
        jPanel3.add(lblPlayer, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        lblComputer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblComputer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icons8_laptop_40px.png"))); // NOI18N
        jPanel4.add(lblComputer, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        lblResult.setLayout(new java.awt.BorderLayout());

        lblRes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icons8_leaderboard_40px.png"))); // NOI18N
        lblResult.add(lblRes, java.awt.BorderLayout.CENTER);

        jPanel2.add(lblResult);

        jPanel6.setLayout(new java.awt.BorderLayout());

        btnRock.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnRock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icons8_rock_48px.png"))); // NOI18N
        btnRock.setText("Rock");
        btnRock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRockActionPerformed(evt);
            }
        });
        jPanel6.add(btnRock, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        btnPaper.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icons8_paper_40px.png"))); // NOI18N
        btnPaper.setText("Paper");
        btnPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaperActionPerformed(evt);
            }
        });
        jPanel7.add(btnPaper, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());

        btnScissors.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btnScissors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icons8_scissors_30px.png"))); // NOI18N
        btnScissors.setText("Scissors");
        btnScissors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScissorsActionPerformed(evt);
            }
        });
        jPanel8.add(btnScissors, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel8);

        jPanel9.setLayout(new java.awt.BorderLayout());

        btnStart.setBackground(new java.awt.Color(51, 51, 255));
        btnStart.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        btnStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico/icons8_play_64px.png"))); // NOI18N
        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        jPanel9.add(btnStart, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel9);

        jPanel10.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel10);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Created by @neexal ");
        jPanel11.add(jLabel2, java.awt.BorderLayout.CENTER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("July,2020");
        jPanel11.add(jLabel3, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(jPanel11);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(256, 256, 256))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaperActionPerformed

        lblPlayer.setText("You Choosed Paper");
        lblComputer.setVisible(true);
        System.out.println("result no: " + chc);
        if (chc == 0){
            lblRes.setText("You Won!");
            
        }
        else if (chc == 2){
            lblRes.setText("You Lost!");
        }
        else{
            lblRes.setText("Draw");
        }
        btnPaper.setEnabled(false);
        btnRock.setEnabled(false);
        btnScissors.setEnabled(false);
    }//GEN-LAST:event_btnPaperActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        lblPlayer.setText("");
        lblRes.setText("");
        btnRock.setEnabled(true);
        btnPaper.setEnabled(true);
        btnScissors.setEnabled(true);
        int random = ThreadLocalRandom.current().nextInt(0, 2 + 1);
        if(random == 0){
            lblComputer.setText("The Computer Choosed Rock");
            chc = 0;
            System.out.println("random no: " + chc);
        }
        else if(random == 1){
            lblComputer.setText("The Computer Choosed Paper");
            chc = 1;
            System.out.println("random no: " + chc);
        }
        else{
            lblComputer.setText("The Computer Choosed Scissor");
            chc = 2;
            System.out.println("random no: " + chc);
        }
        lblComputer.setVisible(false);
        
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnRockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRockActionPerformed

        lblPlayer.setText("You Choosed Rock");
        lblComputer.setVisible(true);
        if (chc == 2){
            lblRes.setText("You Won!");
        }
        else if (chc == 1){
            lblRes.setText("You Lost!");
        }
        else{
            lblRes.setText("Draw");
        }
        btnPaper.setEnabled(false);
        btnRock.setEnabled(false);
        btnScissors.setEnabled(false);
    }//GEN-LAST:event_btnRockActionPerformed

    private void btnScissorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScissorsActionPerformed

        lblPlayer.setText("You Choosed Scissors");
        lblComputer.setVisible(true);
        if (chc == 1){
            lblRes.setText("You Won!");
        }
        else if (chc == 0){
            lblRes.setText("You Lost!");
        }
        else{
            lblRes.setText("Draw");
        }
        btnPaper.setEnabled(false);
        btnRock.setEnabled(false);
        btnScissors.setEnabled(false);
    }//GEN-LAST:event_btnScissorsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPaper;
    private javax.swing.JButton btnRock;
    private javax.swing.JButton btnScissors;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblComputer;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblRes;
    private javax.swing.JPanel lblResult;
    // End of variables declaration//GEN-END:variables
}
